export function returnDummyData() {
    return [
            {
                spillested: "Det Akademiske Kvarter",
                spillestedid: "60",
                navn: "My Story: Overlevelse i perfeksjonens tidsalder",
                sted: "Maos Lille Røde",
                longitude: "8.46895",
                latitude: "60.472",
                stedid: "3",
                arrid: "14204",
                eventlastchanged: "2019-03-05 13:17:40",
                dato: "2019-03-29",
                datoslutt: "2019-03-29",
                datostart: "2019-03-28",
                datoshowto: "2019-03-28",
                link: "https://www.linticket.no/page/no/60/-/14204",
                starttid: "20:00",
                slutttid: "21:15",
                starter: "20:00:00",
                slutt: "24:00:00",
                arrangoernavn: "Bergen Kristne Studentlag (814)",
                arrangoerid: "819",
                age: "0",
                tekst: "",
                teaser: "",
                typeid: "15",
                lengdegrad: "8.46895",
                breddegrad: "60.472",
                typenavn: "Seminar"
            },
            {
                spillested: "Det Akademiske Kvarter",
                spillestedid: "60",
                navn: "Et stort event happening",
                sted: "Teglverket",
                longitude: "8.46895",
                latitude: "60.472",
                stedid: "3",
                arrid: "14204",
                eventlastchanged: "2019-03-05 13:17:40",
                dato: "2019-03-29",
                datoslutt: "2019-03-28",
                datostart: "2019-03-28",
                datoshowto: "2019-03-28",
                link: "https://www.linticket.no/page/no/60/-/14204",
                starttid: "20:00",
                slutttid: "21:15",
                starter: "20:00:00",
                slutt: "24:15:00",
                arrangoernavn: "Øyvind The Master",
                arrangoerid: "819",
                age: "0",
                tekst: "",
                teaser: "",
                typeid: "15",
                lengdegrad: "8.46895",
                breddegrad: "60.472",
                typenavn: "Seminar"
                },
                {
                spillested: "Det Akademiske Kvarter",
                spillestedid: "60",
                navn: "Speed Dating",
                sted: "Troferommet",
                longitude: "8.46895",
                latitude: "60.472",
                stedid: "3",
                arrid: "14204",
                eventlastchanged: "2019-03-05 13:17:40",
                dato: "2019-03-29",
                datoslutt: "2019-03-28",
                datostart: "2019-03-28",
                datoshowto: "2019-03-28",
                link: "https://www.linticket.no/page/no/60/-/14204",
                starttid: "20:00",
                slutttid: "21:15",
                starter: "20:00:00",
                slutt: "24:15:00",
                arrangoernavn: "Bergen Dating",
                arrangoerid: "819",
                age: "0",
                tekst: "",
                teaser: "",
                typeid: "15",
                lengdegrad: "8.46895",
                breddegrad: "60.472",
                typenavn: "Seminar"
                },
                {
                    spillested: "Det Akademiske Kvarter",
                    spillestedid: "60",
                    navn: "Fiske",
                    sted: "Troferommet",
                    longitude: "8.46895",
                    latitude: "60.472",
                    stedid: "3",
                    arrid: "14204",
                    eventlastchanged: "2019-03-05 13:17:40",
                    dato: "2019-03-29",
                    datoslutt: "2019-03-19",
                    datostart: "2019-03-19",
                    datoshowto: "2019-03-19",
                    link: "https://www.linticket.no/page/no/60/-/14204",
                    starttid: "21:30",
                    slutttid: "22:30",
                    starter: "21:30:00",
                    slutt: "24:30:00",
                    arrangoernavn: "Fiskemannen",
                    arrangoerid: "819",
                    age: "0",
                    tekst: "",
                    teaser: "",
                    typeid: "15",
                    lengdegrad: "8.46895",
                    breddegrad: "60.472",
                    typenavn: "Seminar"
                    },
                    {
                        spillested: "Det Akademiske Kvarter",
                        spillestedid: "60",
                        navn: "Fiske",
                        sted: "Stjernesalen",
                        longitude: "8.46895",
                        latitude: "60.472",
                        stedid: "3",
                        arrid: "14204",
                        eventlastchanged: "2019-03-05 13:17:40",
                        dato: "2019-03-29",
                        datoslutt: "2019-03-19",
                        datostart: "2019-03-19",
                        datoshowto: "2019-03-19",
                        link: "https://www.linticket.no/page/no/60/-/14204",
                        starttid: "21:30",
                        slutttid: "24:00",
                        starter: "21:30:00",
                        slutt: "24:30:00",
                        arrangoernavn: "Fiskemannen",
                        arrangoerid: "819",
                        age: "0",
                        tekst: "",
                        teaser: "",
                        typeid: "15",
                        lengdegrad: "8.46895",
                        breddegrad: "60.472",
                        typenavn: "Seminar"
                        }
      ]
}